# This is a minimal values file
# An example of all possible usages can be found here:
# https://github.com/3lvia/kubernetes-charts/blob/master/elvia-deployment/values.yaml

name: {{cookiecutter.application_name}}
namespace: {{cookiecutter.system_name}}
microserviceType: webapp
replicaCount: 2

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
- name: ASPNETCORE_URLS
  value: http://+:8080

service:
 port: 80
 targetPort: 8080

# Subdomains are created in https://github.com/3lvia/dns-terraform
# The port self service action does not create this automatically
ingress:
  subdomain: {{cookiecutter.sub_domain_name}}
  path: "/"

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

livenessProbe:
  failureThreshold: 5
  httpGet:
    path: /
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

startupProbe:
  failureThreshold: 30
  httpGet:
    path: /
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 3
  successThreshold: 1
  timeoutSeconds: 2
