name: Build and deploy {{cookiecutter.application_name}}

on:
  push:
    branches: [trunk]
    paths:
      - "{{cookiecutter.base_dir}}/**"
      - ".github/workflows/build-deploy-{{cookiecutter.application_name}}.yml"
      - ".github/deploy/values-{{cookiecutter.application_name}}.yaml"
  pull_request:
    branches: [trunk]
    paths:
      - "{{cookiecutter.base_dir}}/**"
      - ".github/workflows/build-deploy-{{cookiecutter.application_name}}.yml"
      - ".github/deploy/values-{{cookiecutter.application_name}}.yaml"

permissions:
  actions: read
  contents: read
  id-token: write
  security-events: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  unittests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: 3lvia/core-github-actions-templates/unittest@trunk
        with: 
          working-directory: {{cookiecutter.base_dir}}/

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/trunk' # only run analyze on PR
    steps:
      - uses: 3lvia/core-github-actions-templates/analyze@trunk
        with: 
          working-directory: {{cookiecutter.base_dir}}/

  build:
    name: Build and Scan
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: 3lvia/core-github-actions-templates/build@trunk
        with:
          name: {{cookiecutter.application_name}}
          namespace: {{cookiecutter.system_name}}
          dockerfile: {{cookiecutter.base_dir}}/Dockerfile
          AZURE_CLIENT_ID: {% raw %}${{ vars.ACR_CLIENT_ID }}{% endraw %}

  deploy_dev:
    name: Deploy Dev
    needs: [build, unittests]
    runs-on: ubuntu-latest
    environment: dev
    if: github.ref == 'refs/heads/trunk'
    steps:
      - uses: 3lvia/core-github-actions-templates/deploy@trunk
        with:
          name: {{cookiecutter.application_name}}
          namespace: {{cookiecutter.system_name}}
          environment: dev
          AZURE_CLIENT_ID: {% raw %}${{ vars.AKS_CLIENT_ID }}{% endraw %}
          helm-values-path: '.github/deploy/values-{{cookiecutter.application_name}}.yaml'

  # deploy_test:
  #   name: Deploy Test
  #   needs: [deploy_dev]
  #   runs-on: ubuntu-latest
  #   environment: test
  #   if: github.ref == 'refs/heads/trunk'
  #   steps:
  #     - uses: 3lvia/core-github-actions-templates/deploy@trunk
  #       with:
  #         name: {{cookiecutter.application_name}}
  #         namespace: {{cookiecutter.system_name}}
  #         environment: test
  #         AZURE_CLIENT_ID: {% raw %}${{ vars.AKS_CLIENT_ID }}{% endraw %}
  #         helm-values-path: '.github/deploy/values-{{cookiecutter.application_name}}.yaml'

  # deploy_prod:
  #   name: Deploy Prod
  #   needs: [deploy_test]
  #   runs-on: ubuntu-latest
  #   environment: prod
  #   if: github.ref == 'refs/heads/trunk'
  #   steps:
  #     - uses: 3lvia/core-github-actions-templates/deploy@trunk
  #       with:
  #         name: {{cookiecutter.application_name}}
  #         namespace: {{cookiecutter.system_name}}
  #         environment: prod
  #         AZURE_CLIENT_ID: {% raw %}${{ vars.AKS_CLIENT_ID }}{% endraw %}
  #         helm-values-path: '.github/deploy/values-{{cookiecutter.application_name}}.yaml'
