[project]
name = "{{cookiecutter.application_name}}"
version = "0.1.0"
description = "Simple Python API using FastAPI and uv."
readme = "README.md"
requires-python = ">={{cookiecutter.python_version}}"
dependencies = [
    "fastapi[standard]>=0.112.1",
]
